### REGISTER user
POST http://localhost/register
Content-Type: application/x-www-form-urlencoded
Accept: text/plain

name=Сергей Сидоров&email=sidorov@example.my&phone=792812345678&pass=qwerty

### LOGIN user
POST http://localhost/login
Content-Type: application/x-www-form-urlencoded
Accept: text/plain

email=sidorov@example.my&pass=qwerty

### LOGOUT user
POST http://localhost/logout
Content-Type: application/x-www-form-urlencoded
Accept: text/plain


### FORGOT password
POST http://localhost/forgot
Content-Type: application/x-www-form-urlencoded
Accept: text/plain

email=sidorov@example.my

### OTP for password
POST http://localhost/otp
Content-Type: application/x-www-form-urlencoded
Accept: text/plain

email=sidorov@example.my&otp=794201

### SET NEW password
POST http://localhost/password
Content-Type: application/x-www-form-urlencoded
Accept: text/plain

email=sidorov@example.my&pass=qwerty

### BALANCE
GET http://localhost/balance
Accept: application/json

### DELIVERY
POST http://localhost/delivery
Content-Type: application/json
Accept: text/plain

{
  "track": "",
  "weight": 100.0,
  "worth": 200.0,
  "origin": {
    "address": "street1",
    "state": "country1",
    "phone": "777-77-77",
    "others": "none"
  },
  "destinations": [
    {
      "address": "street2",
      "state": "country2",
      "phone": "555-55-55"
    }
  ]
}

### SHOW delivery package
GET http://localhost/delivery/R-4681c24a-ee38-4935-904c-0b4855bcb899
Accept: application/json

###