### GET users
GET http://localhost/users
Accept: application/json

### GET user
GET http://localhost/user/999
Accept: application/json

### GET name
GET http://localhost/name?id=999
Accept: text/plain

### DELETE user
DELETE http://localhost/user/999
Accept: text/plain

name = Сергей Сидоров

### POST new user
POST http://localhost/new
Content-Type: application/json
Accept: text/plain

{
  "id": 999,
  "name": "Пётр Иванов",
  "points": 1000,
  "clicks": 0,
  "question": 0,
  "answer": 0
}

### POST updated user
POST http://localhost/user
Content-Type: application/json
Accept: text/plain

{
  "id": 999,
  "name": "Иван Петров",
  "points": 2000,
  "clicks": 0,
  "question": 0,
  "answer": 0
}

### user realtime channel
WEBSOCKET ws://localhost/user

### user realtime channel 2
WEBSOCKET ws://localhost/user

###