### GET users
GET http://localhost/users
Accept: application/json

### GET user
GET http://localhost/user/999
Accept: application/json

### GET name
GET http://localhost/name?id=999
Accept: text/plain

### DELETE user
DELETE http://localhost/user/999
Accept: text/plain

### POST new user name
POST http://localhost/add
Content-Type: application/x-www-form-urlencoded
Accept: text/plain

name = Сергей Сидоров

### POST new user
POST http://localhost/new
Content-Type: application/json
Accept: text/plain

{
  "id": 999,
  "name": "Пётр Иванов"
}

### POST updated user
POST http://localhost/user
Content-Type: application/json
Accept: text/plain

{
  "id": 999,
  "name": "Иван Петров"
}

### Hello
GET http://localhost/hello
Cookie: user_session=id%3D%2523s17495132-9b33-45d0-8b29-7d1735a98a01%26name%3D%2523sivan%2540mail.ru
Accept: application/json

### LOGIN
POST http://localhost/login
Content-Type: application/x-www-form-urlencoded
Accept: application/json

mail=ivan@mail.ru&pass=123

### OTP
POST http://localhost/otp
Content-Type: application/x-www-form-urlencoded
Accept: text/plain

mail=ivan@mail.ru

### CHECK
POST http://localhost/check
Content-Type: application/x-www-form-urlencoded
Accept: application/json

mail=ivan@mail.ru&otp=3593

### LOGOUT
POST http://localhost/logout
Cookie: user_session=id%3D%2523s17495132-9b33-45d0-8b29-7d1735a98a01%26name%3D%2523sivan%2540mail.ru
Accept: text/plain

###